development:
  secret_key_base: d6507ff713365a32db4d539ef400680b1517266e35d1108153ec12dfdcd51527af7dc0d6d144f0d22084f247fd270a3355772d2f99a30daab381f7d12c92f156

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  client_id: <%= ENV["CLIENT_ID"] %>
  secret_key: <%= ENV["SECRET_KEY"] %>
  postgres_username: <%= ENV["POSTGRES_USERNAME"] %>
  postgres_password: <%= ENV["POSTGRES_PASSWORD"] %>